"""Michelle on the rail. Short. True. Never jokes about the horse getting hurt."""
from __future__ import annotations

import json
import sys
from pathlib import Path

from rules import EXISTING_RAIL_KEYS, MAX_LINE_WORDS, NEW_RAIL_KEYS

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "content" / "rail" / "michelle.json"
NOTES = ROOT / "content" / "rail" / "barn_notes.json"

SESSIONS = ["lesson", "schooling", "show"]
CLASSES = ["lesson", "beginner", "intermediate", "advanced"]

# 21 existing keys, 18+ each. 17 new keys, 12+ each. All unique.
LINES: dict[str, list[str]] = {
    "early": [
        "Too soon. Wait for the last stride, then ask.",
        "Early. Sit. The stride isn't there yet.",
        "You asked a stride too soon.",
        "Wait. He wasn't there yet.",
        "Don't throw your hand at it early.",
        "Hold. Last stride, then leave.",
        "That leave was a stride early.",
        "Sit quiet. Let the last one come.",
        "You jumped first. He wasn't ready.",
        "Too soon off the ground.",
        "Wait for him. Then ask.",
        "Early to the base. Wait next time.",
        "Don't launch. The stride is later.",
        "You left before the canter finished.",
        "Half-halt, wait, then the leave.",
        "That was early. Come again quieter.",
        "Stay down. Ask on the last one.",
        "He needed one more stride.",
        "Don't anticipate. See it, then leave.",
        "You moved first. Wait for the stride.",
    ],
    "spot": [
        "That was the spot.",
        "Yes. That's the leave.",
        "Good spot. Stay there.",
        "You saw it. Leave like that.",
        "That's the one. Don't fuss after.",
        "Right stride. Pat him later.",
        "That leave was true.",
        "You waited, then asked. That's it.",
        "Spot. Sit still on the other side.",
        "That's the distance. Keep it.",
        "Quiet leave. That's the one.",
        "You found it. Don't chase the next.",
        "Good. Last stride, then the ask.",
        "That's seeing it. Do it again.",
        "True leave. He jumped with you.",
        "That's the spot. Eyes up now.",
        "Yes. Don't throw it away after.",
        "You left with him. Remember that.",
        "That's the picture. Hold it.",
        "Good distance. Sit and let him land.",
    ],
    "deep": [
        "A little deep. Make the last stride.",
        "Deep. Don't add when it's gone.",
        "You got there late. Ride the last one.",
        "Deep to the base. Make the canter.",
        "He left from deep. Don't freeze.",
        "Too deep. Keep the last stride honest.",
        "You waited too long. Ask sooner.",
        "Deep. Half-halt earlier next time.",
        "He chipped from deep. Ride forward.",
        "Late to the spot. Make the stride.",
        "Don't bury him. Leave on the last one.",
        "Deep leave. Come again with more canter.",
        "You held too long. He got deep.",
        "Make the last canter stride.",
        "Deep. Don't pull when you miss it.",
        "He left from the bottom. Ride up.",
        "You got in tight. Keep the canter.",
        "Deep to the rail. See it sooner.",
        "Don't wait into the base.",
        "A stride deeper than you wanted.",
    ],
    "chip": [
        "Chip. Don't get there on a half stride.",
        "He chipped. Make the last one next time.",
        "Chip. That's a half stride, not a leave.",
        "Don't chip. Wait or leave. Not both.",
        "He put in a short one. Ride the canter.",
        "Chip. You didn't make the last stride.",
        "Half stride. That's how rails happen.",
        "Don't pick. Leave or wait.",
        "He chipped in. Keep the canter honest.",
        "Short stride in front. Don't do that.",
        "Chip. See it one stride sooner.",
        "You got there on a half. Don't.",
        "He added a short one. Ride forward.",
        "Chip. That's not the leave.",
        "Don't squeeze a stride that isn't there.",
        "Short to the base. Make the canter.",
        "He chipped. Sit and come again.",
        "Half-stride leave. Wait next time.",
        "Chip. Eyes up and ride the last one.",
        "That extra short one costs a rail.",
    ],
    "looked": [
        "He looked. Straight and quiet.",
        "He peeked. Don't look with him.",
        "Looky. Eyes up. Keep the canter.",
        "He saw it. You stay straight.",
        "He looked. Don't drop your hand.",
        "Quiet. He looked and still jumped.",
        "He noticed the box. You ignore it.",
        "Looky to the flower. Straighten.",
        "He looked. Don't punish the peek.",
        "Keep your eyes up. He'll follow.",
        "He looked. Sit still. Don't chase.",
        "Brush made him look. Ride past it.",
        "He peeked. Leg on, eyes up.",
        "Don't stare at what he's looking at.",
        "He looked and went. Leave him alone.",
        "Looky. Straight. Don't pick at him.",
        "He saw the filler. You see the distance.",
        "Quiet over the look. That's enough.",
        "He looked. Come again the same way.",
        "Don't make his look into a stop.",
    ],
    "wrong": [
        "That's not the next fence.",
        "Wrong fence. Come back to the number.",
        "Not that one. Look at the numbers.",
        "Off the track. That's not next.",
        "Wrong jump. Circle and find the line.",
        "That's not the order. Come again.",
        "You jumped the wrong one.",
        "Not next. Eyes up, find the number.",
        "That's a different fence. Come back.",
        "Wrong. Schooling is still in order.",
        "Not the line. Find the next number.",
        "You left over the wrong fence.",
        "That's not it. Walk, then find one.",
        "Wrong fence. Don't keep going.",
        "Check the numbers. That wasn't next.",
        "Come back. That's not the track.",
        "Not that oxer. The next number.",
        "You cut to the wrong one.",
        "That's out of order. Start the line again.",
        "Wrong jump. I'm not counting that.",
    ],
    "rail": [
        "Rail. He left late.",
        "Rail. That's a late leave.",
        "Down. He got there deep.",
        "Rail. Don't chip the back one.",
        "That's a rail. Sit up and come again.",
        "He rapped it. Late off the ground.",
        "Rail. Make the last stride next time.",
        "Down behind. Don't leave from deep.",
        "Rail. You waited into the base.",
        "That's four. Leave with him next time.",
        "He hit the back rail. Square the oxer.",
        "Rail. Don't pick at the last stride.",
        "Down. Eyes up. Don't look at the pole.",
        "He left late and paid for it.",
        "Rail. Come again to the same fence.",
        "That's a rail. Pat him anyway.",
        "He caught it. Too deep to the base.",
        "Rail. Don't throw your body at it.",
        "Down. The leave wasn't there.",
        "He hit it. Ride the canter, not the rail.",
    ],
    "refuse": [
        "Whoa. Come again to the same fence.",
        "He stopped. Walk, then the same one.",
        "Refusal. Come again quiet.",
        "He said no. Don't chase the second time.",
        "Stop. Straighten and come again.",
        "He refused. Sit. Same fence.",
        "Whoa. Don't turn away angry.",
        "He stopped. You weren't with him.",
        "Refusal. Walk a circle, same line.",
        "He said not yet. Come again quieter.",
        "Stop. Don't kick him at it now.",
        "He refused. Check your line first.",
        "Whoa. Same fence. Don't make a fight.",
        "He stopped. Eyes up and try again.",
        "Refusal. Straight. Then the leave.",
        "He said no. You look next time.",
        "Stop. Pat him. Come again.",
        "He refused. Don't run at it now.",
        "Whoa. I'm still counting this fence.",
        "He stopped. Ride the last stride, then ask.",
    ],
    "off_course": [
        "Off course. That's elimination.",
        "Wrong fence in the show. That's out.",
        "Off course. The round is over.",
        "That's elimination. Off course.",
        "You jumped out of order. That's out.",
        "Off course. Walk him out.",
        "Wrong number in the show. Elimination.",
        "That's out. Off course.",
        "The order matters. That's elimination.",
        "Off course. Pat him and walk.",
        "Show's over. You left the track.",
        "That's elimination. Come get him.",
        "Off course. Don't keep jumping.",
        "Wrong fence under Table A. Out.",
        "That's the end. Off course.",
        "Elimination. You missed the number.",
        "Off course. We're done here.",
        "Out of order. That's a stop.",
        "That's elimination. Walk back.",
        "Off course. Save him for later.",
    ],
    "three": [
        "Three refusals. That's the end of the round.",
        "Third stop. That's elimination.",
        "Three. We're done.",
        "That's three refusals. Walk him out.",
        "Third no. The round is over.",
        "Three stops. That's the end.",
        "Elimination. Three refusals.",
        "That's three. Pat him and walk.",
        "Third refusal. Don't keep at it.",
        "Three. Come get him.",
        "That's the end. Three refusals.",
        "Third stop. We're finished.",
        "Three nos. Walk him. That's enough.",
        "Elimination on three. School it later.",
        "That's three. No more fences today.",
        "Third refusal. The clock is done.",
        "Three. Don't make the fourth a fight.",
        "That's the round. Three refusals.",
        "Third stop. Take him home quiet.",
        "Three refusals. We're out.",
    ],
    "time": [
        "Time limit. That's the end of the round.",
        "That's time. The round is over.",
        "Time. Walk him out.",
        "The limit's gone. That's elimination.",
        "Time allowed is twice over. We're done.",
        "That's time. Don't keep running.",
        "Clock's done. Walk.",
        "Time limit. Pat him and come back.",
        "That's the end. Time.",
        "Over the limit. The round is finished.",
        "Time. We're out.",
        "That's time elimination. Walk him.",
        "The clock stopped you. That's enough.",
        "Time limit. Don't chase now.",
        "That's time. School it without the clock.",
        "Over time. Come get him.",
        "The limit's up. Walk out.",
        "Time. Save the rest for schooling.",
        "That's the clock. Round over.",
        "Time limit. We're finished.",
    ],
    "lesson_start": [
        "Walk him first. Then pick up the canter.",
        "Walk first. Canter before the flags.",
        "Walk him. Don't canter from the gate.",
        "Start at walk. He isn't ready yet.",
        "Walk a lap. Then the canter.",
        "Walk him first. Wait for the last stride.",
        "Walk. Then trot. Then the canter.",
        "Don't run to the first fence.",
        "Walk him. I'm watching the leave.",
        "Start quiet. Walk, then canter.",
        "Walk first. Flags after you have a canter.",
        "Walk him around. Then we jump.",
        "Lesson. Walk him. Then the poles.",
        "Walk first. Don't skip that.",
        "Get a walk. Then a canter. Then ask.",
        "Walk him. Pick up the canter before in.",
        "Quiet start. Walk, then the line.",
        "Walk first. He needs to blow.",
        "Don't canter in from the barn.",
        "Walk him. Then we'll see a distance.",
    ],
    "jump_off": [
        "Jump-off. Four fences. Don't chase him.",
        "Jump-off. Don't throw the first one away.",
        "Four fences. Sit. The clock is enough.",
        "Jump-off. Leave, then wait.",
        "Don't chase. Four fences, that's all.",
        "Jump-off. Inside turns, not a gallop.",
        "Four. Keep the canter you had.",
        "Jump-off. Don't make this a race.",
        "Sit. Four fences. He knows the way.",
        "Jump-off. Wait for the last stride.",
        "Don't run. The time is already tight.",
        "Four fences. Eyes up. Don't cut ugly.",
        "Jump-off. Same leave, shorter track.",
        "Don't throw the first jump-off fence.",
        "Jump-off. Pat him after, not during.",
        "Four. Straight. Then the turn.",
        "Jump-off. I'm still watching the leave.",
        "Don't hurry the distance. Four fences.",
        "Jump-off. Sit down and wait.",
        "Four fences. Leave with him, then wait.",
    ],
    "clear": [
        "That's a clear. Pat him and walk out.",
        "Clear. Walk him. Let him blow.",
        "That's a clear. Don't school it now.",
        "Clear. Pat him.",
        "That's clean. Walk out quiet.",
        "Clear round. Get off while it's good.",
        "That's a clear. He did his job.",
        "Clean. Walk him around the barn.",
        "That's a clear. No extra fences.",
        "Clear. Sit. Walk.",
        "That's clean. Pat him and be done.",
        "Clear round. Don't pick at him now.",
        "That's a clear. Good enough.",
        "Clean. Walk him out of the ring.",
        "That's a clear. Thank him.",
        "Clear. Leave the ring like you meant it.",
        "That's clean. We're finished.",
        "Clear round. Walk, then the barn.",
        "That's a clear. Don't grin at the oxer.",
        "Clean. He jumped. You waited. Walk.",
    ],
    "ribbon": [
        "Ribbon. Don't get sloppy now.",
        "That's a ribbon. Walk him out.",
        "Ribbon. Pat him. Don't make a speech.",
        "You got a ribbon. Stay quiet.",
        "Ribbon. Don't throw the next round away.",
        "That's a color. Walk out like you ride.",
        "Ribbon. He earned it. You sat.",
        "Don't wave it. Pat him.",
        "Ribbon. Schooling still matters tomorrow.",
        "That's a ribbon. Come get him.",
        "Ribbon. Eyes up until you're out.",
        "Don't get sloppy because of a ribbon.",
        "That's a color. Walk. Then the barn.",
        "Ribbon. I'm still watching the halt.",
        "You pinned. Don't change the leave.",
        "Ribbon. Thank him, not the crowd.",
        "That's a ribbon. Quiet face.",
        "Don't drop him now. Ribbon or not.",
        "Ribbon. Walk out on a long rein.",
        "That's a color. Be done with it.",
    ],
    "steady": [
        "Steady. Sit. Let him find it.",
        "Steady. Don't hurry the canter.",
        "Sit still. Steady the last stride.",
        "Steady. He can see it if you wait.",
        "Don't chase. Steady.",
        "Steady the canter. Then the leave.",
        "Sit. Steady. Eyes up.",
        "Steady. Half-halt, then leave him.",
        "Don't pick. Steady the rhythm.",
        "Steady. The distance comes from that.",
        "Keep him steady. Don't invent a stride.",
        "Steady canter. That's the whole job.",
        "Sit quiet. Steady to the base.",
        "Steady. I'm not asking for more pace.",
        "Don't run. Steady and wait.",
        "Steady. He jumps better than you hurry.",
        "Keep the canter steady around the turn.",
        "Steady. Last stride, then ask.",
        "Don't move. Steady him to it.",
        "Steady. Let the stride come.",
    ],
    "walk_out": [
        "Walk him out. Let him blow.",
        "Walk. Long rein. Let him breathe.",
        "Walk him out. That's enough jumping.",
        "Walk. Don't trot around now.",
        "Walk him. Let the canter come down.",
        "Walk out. Pat him.",
        "Walk. We're done in here.",
        "Walk him out of the ring.",
        "Long walk. Let him blow.",
        "Walk. He jumped. Now he walks.",
        "Walk him out. Don't school the halt.",
        "Walk. Loosen the rein.",
        "Walk him. That's the end of the work.",
        "Walk out quiet. No extra fences.",
        "Walk. Let him stretch.",
        "Walk him around. Then the barn.",
        "Walk out. I'm finished talking.",
        "Walk. He earned the walk.",
        "Walk him. Don't keep cantering.",
        "Walk out. Then put him away.",
    ],
    "halt": [
        "Whoa means whoa. Sit down.",
        "Halt. Sit. Don't pull.",
        "Whoa. He stops when you sit.",
        "Halt means halt. Not almost.",
        "Sit down for the halt.",
        "Whoa. Wait until he stops.",
        "Halt. Leg off, sit, then the hand.",
        "Don't bounce through the halt.",
        "Whoa. Square. Then stand.",
        "Halt. He should stand when you ask.",
        "Sit. Whoa is not a suggestion.",
        "Halt. Don't wiggle him into it.",
        "Whoa. Keep your eyes up.",
        "Halt and stand. That's the whole thing.",
        "Don't halt with your hands only.",
        "Whoa. Sit first.",
        "Halt. Then pat. Not before.",
        "He walked through that halt. Again.",
        "Whoa means stop. Do it again.",
        "Halt. Quiet. Then we walk.",
    ],
    "pat": [
        "Pat him. He tried.",
        "Pat him. That's enough.",
        "Scratch his neck. He jumped.",
        "Pat him. Don't keep talking.",
        "He tried. Pat him and walk.",
        "Pat him. The leave was honest.",
        "Thank him. Pat.",
        "Pat him. Even when it's messy.",
        "He showed up. Pat him.",
        "Pat. Then walk.",
        "Scratch him. He did the work.",
        "Pat him. I'm not mad at him.",
        "He tried. That's worth a pat.",
        "Pat him before you get off.",
        "Hand on his neck. Then walk.",
        "Pat him. Don't skip that.",
        "He waited with you. Pat him.",
        "Pat. Quiet. That's the reward.",
        "Scratch the withers. Walk him out.",
        "Pat him. He doesn't need a speech.",
    ],
    "straight": [
        "Straight. Eyes up. Don't drop him.",
        "Straighten. He jumps the line you ride.",
        "Get straight. Then the leave.",
        "Straight. Don't drift to the standard.",
        "Eyes up. Straight to the middle.",
        "You're crooked. Straighten before you ask.",
        "Straight. The distance lives in the middle.",
        "Don't cut. Straighten, then leave.",
        "Straight to the numbers.",
        "Get even in both reins. Straight.",
        "Straight. He looked because you drifted.",
        "Ride the middle. Straight.",
        "Don't lean. Straight and sit.",
        "Straighten the canter, then the fence.",
        "Eyes up. Middle of the poles.",
        "Straight. I'm watching the shoulders.",
        "Don't drift in. Straighten.",
        "Straight line. Then the last stride.",
        "Get straight off the turn.",
        "Straight. Then wait for the stride.",
    ],
    "leave": [
        "Leave with him. Don't wait after the stride.",
        "Leave. You saw it. Go.",
        "Don't wait once the stride is there.",
        "Leave with him. That's the whole thing.",
        "You saw it. Leave.",
        "Don't freeze at the spot. Leave.",
        "Leave. He already said yes.",
        "When it's there, leave. Don't pick.",
        "Leave with the last stride.",
        "Don't sit past the spot. Leave.",
        "You waited after you saw it. Leave.",
        "Leave. Hands quiet. Leg on.",
        "That's the stride. Leave with him.",
        "Don't second-guess the leave.",
        "Leave. I'm not asking you to wait now.",
        "Go with him. That's a leave.",
        "Don't hold through the spot. Leave.",
        "Leave. He can't do it alone.",
        "You saw the distance. Leave it.",
        "Leave with him, then sit still.",
    ],
    "half_halt": [
        "Half-halt. Then leave him alone.",
        "Half-halt to the last stride.",
        "Sit the half-halt. Don't pull.",
        "Half-halt. Rebalance, then the leave.",
        "That's a half-halt, not a whoa.",
        "Half-halt early. Don't wait to the base.",
        "Sit, half-halt, then go.",
        "Half-halt. Keep the canter.",
        "Don't skip the half-halt.",
        "Half-halt, last stride, then ask.",
        "That's too much hand. Half-halt.",
        "Half-halt off the turn.",
        "Quiet half-halt. Then wait.",
        "Half-halt. He got strong.",
        "Sit down for the half-halt.",
        "Half-halt now. Not at the takeoff.",
    ],
    "crooked": [
        "Crooked. Straighten before you ask.",
        "You're crooked to the standard.",
        "Straighten. He jumped the drift.",
        "Crooked. That's why he looked.",
        "Get even. You're in the left rein.",
        "Crooked off the turn. Fix it.",
        "Don't jump from a crooked canter.",
        "Straighten the shoulders.",
        "Crooked. Middle of the poles.",
        "You're falling in. Straighten.",
        "Crooked to the oxer. Don't.",
        "Get straight. Then the distance.",
        "Crooked. He can't leave from that.",
        "Inside shoulder. Straighten.",
        "Don't cut and stay crooked.",
        "Crooked line. Come again straight.",
    ],
    "long_spot": [
        "Long spot. He covered it. Don't make a habit.",
        "That was long. Wait next time.",
        "Long leave. Don't chase those.",
        "You left long. He has the scope today.",
        "Long spot. Don't throw your body.",
        "That's a long one. Sit quieter.",
        "Long. Next time wait for the last stride.",
        "He stood off. Don't look for that.",
        "Long spot. Pat him. Don't repeat it.",
        "You asked long. He said yes.",
        "That's long. I'm not teaching that.",
        "Long leave. Keep the canter next time.",
        "He left long. You got lucky.",
        "Long spot. Come again and wait.",
        "Don't hunt the long one.",
        "That leave was long. Sit still.",
    ],
    "short_spot": [
        "Short spot. Make the last stride.",
        "You got in short. Ride up.",
        "Short. Don't freeze when it's tight.",
        "That's a short leave. Keep the canter.",
        "Short spot. He still jumped. Don't repeat it.",
        "You waited into a short one.",
        "Short. Half-halt earlier, then leave.",
        "Tight to the base. Ride the last one.",
        "Short spot. Don't chip from there.",
        "That's short. Come again forward.",
        "You got close. Make the stride.",
        "Short leave. Eyes up.",
        "That's a short one. Don't pull.",
        "Short. He saved you. Ride better.",
        "Don't sit and hope. Short leaves add.",
        "Short spot. I'm watching the canter.",
    ],
    "related_in": [
        "Don't move on the in. Sit to the out.",
        "Related in. Leave, then wait.",
        "In of the line. Don't chase.",
        "That's the in. Sit still after.",
        "Related in. I'm watching the out.",
        "Don't pick at the in.",
        "In. Leave him. The out is coming.",
        "That's the in. Count. Don't hurry.",
        "Related in. Quiet hands.",
        "Don't throw the in. The out matters.",
        "In of the two-stride. Sit.",
        "That's the in. Stay in the canter.",
        "Related in. Don't look down.",
        "Leave the in. Wait for the out.",
        "In. He knows the line if you wait.",
        "Don't move. That's the in.",
    ],
    "related_out": [
        "Sit to the out. Let him jump it.",
        "Out. Don't invent a stride.",
        "That's the out. Wait.",
        "Related out. Sit still.",
        "Don't chase the out.",
        "Out of the line. Leave with him.",
        "That's the out. Eyes up.",
        "Related out. I'm done talking.",
        "Sit. The out is his if you wait.",
        "Don't pick at the out.",
        "Out. Same canter you had.",
        "That's the out. Don't freeze.",
        "Related out. Pat him after.",
        "Leave the out. Don't hold.",
        "Out of the two. Don't add.",
        "Sit to the out. That's the job.",
    ],
    "looky_flower": [
        "Flower. Straight and quiet.",
        "He looks at flowers. You don't.",
        "Flower box. Eyes up.",
        "Straight to the flowers. Don't stare.",
        "Looky flower. Leg on, sit still.",
        "He sees the box. You see the stride.",
        "Flower. Don't drop him in front.",
        "Quiet to the flowers.",
        "That's a looky one. Straighten.",
        "Flower box. Same leave as a vertical.",
        "Don't look at the blooms.",
        "Flower. He'll go if you go.",
        "Looky. Ride past the box.",
        "Flowers. I'm watching your eyes.",
        "Straight. The flower isn't the job.",
        "He looked at the box. You stay up.",
    ],
    "oxer": [
        "Oxer. Square. Don't chip the back rail.",
        "See the front. He'll jump the back.",
        "Oxer. Don't leave from deep.",
        "Square to the oxer.",
        "That's an oxer. Make the last stride.",
        "Don't chip the back one.",
        "Oxer. Ride the front rail.",
        "Get even to the oxer.",
        "That's a spread. Don't get short.",
        "Oxer. Sit. Let him bascule.",
        "Don't throw your body at the oxer.",
        "Front rail first. Then the back.",
        "Oxer. I'm watching the leave, not the color.",
        "Square. That's an oxer.",
        "Don't drift. Oxers punish crooked.",
        "Oxer. Wait, then leave with him.",
    ],
    "first_fence": [
        "First fence. Don't move.",
        "Leave the first. Then we talk.",
        "First one. Long approach. Wait.",
        "Don't throw the first fence away.",
        "First fence. Find the canter first.",
        "That's one. Sit still after.",
        "First. I'm watching the leave.",
        "Don't chase the first one.",
        "First fence. Eyes up.",
        "Leave the first quiet.",
        "That's the first. Don't celebrate.",
        "First fence. Same as the rest.",
        "Don't make the first a scene.",
        "First one. Wait for the last stride.",
        "In-gate to the first. Don't run.",
        "First fence. He canters this ring.",
    ],
    "last_fence": [
        "Last fence. Don't throw it away.",
        "That's the last. Same leave.",
        "Last one. Don't get sloppy.",
        "Finish. Wait for the stride.",
        "Last fence. Sit. Then walk.",
        "Don't rush the last one.",
        "That's the last. Eyes up.",
        "Last oxer. Don't chip it.",
        "Finish quiet. That's the last.",
        "Last fence. I'm still watching.",
        "Don't drop him at the last.",
        "That's the last. Leave with him.",
        "Last one. Pat him after, not now.",
        "Finish. Don't look at the out-gate.",
        "Last fence. Same canter.",
        "Don't throw away the last rail.",
    ],
    "whoa": [
        "Whoa. Sit down.",
        "Whoa means stop.",
        "Sit. Whoa.",
        "Whoa. He hears you if you sit.",
        "Don't whoa with your hands only.",
        "Whoa. Then stand.",
        "Sit first. Then whoa.",
        "Whoa. Quiet.",
        "That's a whoa, not a half-halt.",
        "Whoa. Eyes up.",
        "Stop. Whoa means now.",
        "Whoa. Don't bounce.",
        "Sit down and whoa.",
        "Whoa. Wait until he halts.",
        "That's whoa. Do it again if he walked.",
        "Whoa. I'm not asking twice.",
    ],
    "walk_first": [
        "Walk first.",
        "Walk him before you canter.",
        "Walk. Then we jump.",
        "Walk first. He just came out.",
        "Don't canter yet. Walk.",
        "Walk him. I'm not in a hurry.",
        "Walk first. Always.",
        "Walk a lap.",
        "Walk. Let him see the ring.",
        "Walk first. Then the flags.",
        "Start at walk.",
        "Walk him. Then pick up the canter.",
        "Walk. That's not optional.",
        "Walk first. Then the lesson starts.",
        "Walk him until he blows.",
        "Walk. Then trot if he needs it.",
    ],
    "sit": [
        "Sit.",
        "Sit down.",
        "Sit still.",
        "Sit. Don't perch.",
        "Sit the last stride.",
        "Sit. He needs your seat, not your hands.",
        "Sit quiet.",
        "Sit. The leave is from there.",
        "Don't stand up. Sit.",
        "Sit through the turn.",
        "Sit. I'm watching your seat.",
        "Sit down and wait.",
        "Sit. Then the half-halt.",
        "Don't hover. Sit.",
        "Sit the canter.",
        "Sit. That's the aid.",
    ],
    "eyes_up": [
        "Eyes up.",
        "Eyes up. Don't look at the rail.",
        "Look up. The distance is in front.",
        "Eyes up over the flower.",
        "Don't stare at the base. Eyes up.",
        "Eyes up. He follows your look.",
        "Look where you're going.",
        "Eyes up through the turn.",
        "Don't look down at his neck.",
        "Eyes up. Then the leave.",
        "Look at the next fence, not this rail.",
        "Eyes up. I'm watching your head.",
        "Don't duck. Eyes up.",
        "Eyes up to the standards, not the filler.",
        "Look up. That's half the straight.",
        "Eyes up. Then sit.",
    ],
    "confidence_low": [
        "He's looky. Walk, then a quiet canter.",
        "Don't chase him. He's not sure yet.",
        "He's quiet-nervous. Don't make a fight.",
        "Walk him. Confidence isn't a gallop.",
        "He's looky today. Straight and wait.",
        "Don't kick a looky horse at a flower.",
        "He's unsure. You be sure.",
        "Quiet. He's not with you yet.",
        "He's looky. Smaller canter, same leave.",
        "Don't run at it. He's already looking.",
        "Walk, then canter. He's not ready to jump.",
        "He's careful today. Don't hurry him.",
        "Looky. Sit still. He'll go if you go.",
        "Don't chase. He's asking you to wait.",
        "He's not confident. You don't get busy.",
        "Quiet day. Don't pick a fight with him.",
    ],
    "he's_with_you": [
        "He's with you. Don't over-ride him.",
        "He's with you. Let him jump.",
        "Don't fuss. He's already there.",
        "He's with you. Sit and leave.",
        "Leave him alone. He's jumping.",
        "He's with you. Don't add leg now.",
        "Don't over-ride a horse that's with you.",
        "He's there. You wait.",
        "He's with you. Eyes up. That's enough.",
        "Let him jump. He's with you.",
        "Don't pick. He's already said yes.",
        "He's with you. Pat him after.",
        "Sit still. He's doing the work.",
        "He's with you. Don't change the canter.",
        "Leave him. He's already leaving.",
        "He's with you. Don't make it bigger.",
    ],
    "don't_chase": [
        "Don't chase him.",
        "Don't chase the fences.",
        "Don't chase. The clock isn't the leave.",
        "Don't run at it.",
        "Don't chase a distance that isn't there.",
        "Don't chase him off the first.",
        "Don't chase. Sit.",
        "Don't chase the jump-off.",
        "Don't chase. He canters this ring.",
        "Don't run. Wait for the last stride.",
        "Don't chase a looky horse.",
        "Don't chase after a rail.",
        "Don't chase. I'm not asking for pace.",
        "Don't chase him to the oxer.",
        "Don't chase the out of the line.",
        "Don't chase. Leave, then wait.",
    ],
}

# Expand pass: more unique barn-voice lines, still under 14 words.
MORE: dict[str, list[str]] = {
    "early": [
        "You left a stride too soon again.",
        "Early. Come again and wait.",
        "Don't jump until the last stride is there.",
        "Too soon off the turn.",
    ],
    "spot": [
        "That's the leave I wanted.",
        "Good. Don't change anything.",
        "You waited. That's the spot.",
        "True distance. Remember the feel.",
    ],
    "deep": [
        "Deep again. Ride the last canter stride.",
        "You got in tight. Don't freeze next time.",
        "Late. Make the stride, don't hope.",
        "Deep to the oxer. Don't do that.",
    ],
    "chip": [
        "Chip again. That's not a leave.",
        "He put in a half. Ride forward.",
        "Don't chip the back rail of an oxer.",
        "Short stride. See it sooner.",
    ],
    "looked": [
        "He looked at the brush. You didn't.",
        "Peeked and went. Leave him alone.",
        "Looky to the box. Keep the line.",
        "He saw it. You stayed straight. Good.",
    ],
    "wrong": [
        "Not that number. Come back.",
        "Wrong line. Find the next fence.",
        "That's the other oxer. Not next.",
        "Off the numbers. Walk and look.",
    ],
    "rail": [
        "Rail behind. Late leave.",
        "He rapped the front. Too deep.",
        "That's four faults. Come again.",
        "Down. Don't look at it.",
    ],
    "refuse": [
        "He stopped at the flower. Same one again.",
        "Refusal. Walk. Then the same line.",
        "He said no. You weren't straight.",
        "Stop. Don't make the second a fight.",
    ],
    "off_course": [
        "Wrong number. That's the show over.",
        "Off the track. Elimination.",
        "You left the course. Walk him.",
        "That's out. Off course under Table A.",
    ],
    "three": [
        "Third no. Walk him to the barn.",
        "Three stops. That's enough.",
        "Elimination. Three refusals, we're done.",
        "Third refusal. Don't keep jumping.",
    ],
    "time": [
        "The clock got you. Walk.",
        "Time's gone. That's the round.",
        "Over the limit. Come back.",
        "That's time. No more fences.",
    ],
    "lesson_start": [
        "Walk him. Then we pick up the canter.",
        "Lesson starts at walk. Not the first fence.",
        "Walk a circle. Then the poles.",
        "Walk first. I'm not watching a gallop.",
    ],
    "jump_off": [
        "Four fences. Don't throw the turn away.",
        "Jump-off. Same horse, shorter track.",
        "Don't gallop. Four leaves.",
        "Jump-off. Wait. Then the inside turn.",
    ],
    "clear": [
        "Clear. Get off him while it's good.",
        "That's clean. Walk out of the ring.",
        "Clear round. No extra.",
        "Clean. He jumped. You waited.",
    ],
    "ribbon": [
        "That's a ribbon. Halt square.",
        "You pinned. Walk out quiet.",
        "Ribbon. Don't drop the last halt.",
        "Color. Pat him, not the rail.",
    ],
    "steady": [
        "Steady the last three strides.",
        "Don't hurry. Steady him.",
        "Steady. That's how you see it.",
        "Keep him steady off the corner.",
    ],
    "walk_out": [
        "Walk him. We're finished jumping.",
        "Long rein. Walk out.",
        "Walk. Let him blow before the stall.",
        "Walk him around the barn once.",
    ],
    "halt": [
        "Halt square. Then stand.",
        "Whoa. Don't let him walk through it.",
        "Halt. Sit until he stops.",
        "That's not a halt. Do it again.",
    ],
    "pat": [
        "Scratch him. Then we walk.",
        "Pat. He doesn't need more words.",
        "Hand on his neck. Good.",
        "Pat him. That's the end of it.",
    ],
    "straight": [
        "Straighten before the last stride.",
        "You're in the right standard. Straighten.",
        "Middle. Straight. Then leave.",
        "Get straight off that rollback.",
    ],
    "leave": [
        "That's the stride. Go with him.",
        "Don't sit past it. Leave.",
        "You saw it. Don't wait now.",
        "Leave. Quiet hands.",
    ],
    "half_halt": [
        "Half-halt off the corner, not the base.",
        "That's a pull. I wanted a half-halt.",
        "Half-halt. Then leave the canter.",
        "Sit the half-halt earlier.",
    ],
    "crooked": [
        "Crooked to the flower. That's why he looked.",
        "Straighten the rollback.",
        "You're falling out. Straighten.",
        "Crooked. I can see both standards.",
    ],
    "long_spot": [
        "Long again. Don't hunt that.",
        "He stood off. Not the school.",
        "Long leave. Wait next time.",
        "That's long. He covered. Don't repeat.",
    ],
    "short_spot": [
        "Short again. Ride the last one.",
        "You got close. Don't freeze.",
        "Tight leave. Keep the canter.",
        "Short. Come again forward.",
    ],
    "related_in": [
        "In. Don't move your hands.",
        "That's the in. Count two.",
        "Related in. I'm watching your seat.",
        "Leave the in quiet.",
    ],
    "related_out": [
        "Out. Don't add a stride.",
        "That's the out. Same canter.",
        "Sit. The out is there.",
        "Related out. Don't look down.",
    ],
    "looky_flower": [
        "Flower again. Eyes up.",
        "He looks at pink. You don't.",
        "Box. Straight. Same leave.",
        "Flowers. Ride the middle.",
    ],
    "oxer": [
        "Square oxer. Front first.",
        "Don't get short to the spread.",
        "Oxer. Make the last stride honest.",
        "Back rail. That's on a chip.",
    ],
    "first_fence": [
        "First one quiet. Then we ride.",
        "Don't miss the first.",
        "First fence. Canter before the flags.",
        "That's one. Don't stand up.",
    ],
    "last_fence": [
        "Last one. Same as the first.",
        "Don't throw the last rail away.",
        "Finish. Wait. Then walk.",
        "Last fence. Eyes still up.",
    ],
    "whoa": [
        "Whoa. Stand.",
        "Sit and whoa. Not the other way.",
        "Whoa. He walked. Again.",
        "That's whoa. Hold it.",
    ],
    "walk_first": [
        "Walk him. Then the canter.",
        "Walk first. Every time.",
        "Don't skip the walk.",
        "Walk until I say canter.",
    ],
    "sit": [
        "Sit the rollback.",
        "Sit. Don't perch to the oxer.",
        "Sit still over the flower.",
        "Sit. That's enough aid.",
    ],
    "eyes_up": [
        "Eyes up to the out-gate.",
        "Don't look at the chip. Eyes up.",
        "Eyes up. The next fence is next.",
        "Look up. He dropped because you did.",
    ],
    "confidence_low": [
        "He's looky. Don't make a scene.",
        "Quiet canter. He's not sure.",
        "Walk more. Then a small fence.",
        "He's careful. You be quieter.",
    ],
    "he's_with_you": [
        "He's jumping. Don't add.",
        "With you. Sit still.",
        "He's there. Don't make it bigger.",
        "Leave him. He's already with you.",
    ],
    "don't_chase": [
        "Don't chase the related out.",
        "Don't run the jump-off.",
        "Don't chase a rail with more pace.",
        "Don't chase. Wait for the stride.",
    ],
}


def word_count(text: str) -> int:
    return len(text.replace("—", " ").split())


def barn_notes() -> list[dict]:
    notes = [
        {
            "id": "lesson_first",
            "text": "Lesson first. Walk him, pick up the canter, and wait for the last stride.",
            "session": ["lesson"],
            "abbott_confidence": [0, 100],
            "abbott_rideability": [0, 100],
            "madison_timing": [0, 100],
        },
        {
            "id": "looky_low_conf",
            "text": "Abbott is looky. Walk him, then a quiet canter. Don't chase the fences.",
            "session": ["schooling", "show"],
            "abbott_confidence": [0, 30],
            "abbott_rideability": [0, 100],
            "madison_timing": [0, 100],
        },
        {
            "id": "fresh_mid_conf",
            "text": "He's a little fresh. Make the last canter stride, then ask.",
            "session": ["schooling", "show"],
            "abbott_confidence": [30, 50],
            "abbott_rideability": [0, 100],
            "madison_timing": [0, 100],
        },
        {
            "id": "with_you",
            "text": "He's with you. Don't over-ride him — let him jump.",
            "session": ["schooling", "show"],
            "abbott_confidence": [65, 100],
            "abbott_rideability": [70, 100],
            "madison_timing": [0, 100],
        },
        {
            "id": "timing_needs_work",
            "text": "Half-halt to the last stride, then let him go. He'll tell you.",
            "session": ["schooling", "show"],
            "abbott_confidence": [50, 100],
            "abbott_rideability": [0, 70],
            "madison_timing": [0, 40],
        },
        {
            "id": "quiet_day",
            "text": "Quiet day at Hidden K. School what you need, or go in the show.",
            "session": ["schooling", "show"],
            "abbott_confidence": [50, 100],
            "abbott_rideability": [0, 100],
            "madison_timing": [40, 100],
        },
    ]
    extras = [
        ("bn_walk_looky", "Walk him until he blows. Then a quiet canter. No flowers yet.", [0, 28], [0, 100], [0, 100], ["schooling"]),
        ("bn_looky_show", "He's looky. Welcome Stake can wait. School the first fence quiet.", [0, 30], [0, 100], [0, 100], ["show"]),
        ("bn_fresh_right", "Fresh. Outside track, right lead. Don't start on a flower.", [30, 48], [0, 100], [0, 100], ["schooling"]),
        ("bn_fresh_show", "He's a little up. Walk in. Don't canter from the gate.", [30, 48], [0, 100], [0, 100], ["show"]),
        ("bn_timing_early", "You're leaving early. Walk a fence. Then wait for the last stride.", [40, 100], [0, 100], [0, 35], ["schooling"]),
        ("bn_timing_deep", "You're getting deep. Make the last canter stride. Don't freeze.", [40, 100], [0, 100], [0, 38], ["schooling"]),
        ("bn_ride_soft", "He's soft in the bridle. Don't pick. Sit and leave.", [50, 100], [60, 100], [40, 100], ["schooling"]),
        ("bn_ride_strong", "He got strong. Half-halt off the turn, not at the base.", [55, 100], [0, 45], [40, 100], ["schooling"]),
        ("bn_conf_ok", "He's brave enough. Don't invent a bigger canter.", [50, 70], [40, 100], [40, 100], ["schooling"]),
        ("bn_conf_high", "He's with you. Classic height is enough. Don't over-ride.", [70, 100], [70, 100], [50, 100], ["schooling"]),
        ("bn_show_quiet", "Show day. Same leave as Tuesday. Don't make it a different horse.", [50, 100], [40, 100], [40, 100], ["show"]),
        ("bn_show_looky", "Looky in the schooling ring. Same fence, quieter canter.", [0, 40], [0, 100], [0, 100], ["show"]),
        ("bn_mini_prix", "Mini Prix. Keep the canter you schooled. Don't chase the clock.", [60, 100], [50, 100], [45, 100], ["show"]),
        ("bn_welcome", "Welcome Stake. Outside track. First fence quiet.", [40, 100], [0, 100], [30, 100], ["show"]),
        ("bn_classic", "Classic. Related in the middle. Don't move on the in.", [50, 100], [40, 100], [40, 100], ["show"]),
        ("bn_lesson_poles", "Poles. Walk, canter, wait. I'm watching the leave, not the height.", [0, 100], [0, 100], [0, 100], ["lesson"]),
        ("bn_lesson_line", "Related two-stride today. Don't move on the in.", [0, 100], [0, 100], [0, 100], ["lesson"]),
        ("bn_lesson_halt", "Halt means halt. We'll jump after he stands.", [0, 100], [0, 100], [0, 100], ["lesson"]),
        ("bn_after_rail", "He had a rail. School the canter, not the fence.", [20, 70], [0, 100], [0, 55], ["schooling"]),
        ("bn_after_stop", "He stopped. Walk, same fence, quieter. Don't kick.", [0, 45], [0, 100], [0, 100], ["schooling"]),
        ("bn_clear_yesterday", "He jumped around yesterday. Don't pick him apart today.", [60, 100], [55, 100], [45, 100], ["schooling"]),
        ("bn_hot_day", "Late summer. Walk more than you think. Then a short school.", [0, 100], [0, 100], [0, 100], ["schooling"]),
        ("bn_wet_ring", "Center's wet. Stay on the outside track until it rides.", [0, 100], [0, 100], [0, 100], ["schooling"]),
        ("bn_dry_ring", "Ring's deep at the in-gate. Make the canter before the flags.", [0, 100], [0, 100], [0, 100], ["schooling"]),
        ("bn_flower_day", "Flower's in. Straight. He looks if you do.", [0, 55], [0, 100], [0, 100], ["schooling"]),
        ("bn_oxer_day", "Oxer's up. Square. Don't chip the back rail.", [40, 100], [0, 100], [30, 100], ["schooling"]),
        ("bn_jo_ready", "If you go clear, stay. Jump-off is four. Don't chase.", [60, 100], [55, 100], [50, 100], ["show"]),
        ("bn_no_jo", "School the course. Jump-off isn't the job today.", [0, 50], [0, 100], [0, 45], ["show"]),
        ("bn_pat_first", "Pat him first. Then we talk about the chip.", [0, 100], [0, 100], [0, 100], ["schooling"]),
        ("bn_eyes", "Eyes up. The distance isn't in the sand.", [0, 100], [0, 100], [0, 50], ["schooling", "lesson"]),
        ("bn_sit", "Sit. He doesn't need a busier rider today.", [40, 100], [50, 100], [0, 100], ["schooling"]),
        ("bn_wait", "Wait for the last stride. That's the whole school.", [0, 100], [0, 100], [0, 45], ["lesson", "schooling"]),
        ("bn_pfafftown", "Quiet Tuesday at Hidden K. School what you need.", [45, 100], [40, 100], [40, 100], ["schooling"]),
        ("bn_abbott", "Abbott's a chestnut who tries. Don't chase him.", [0, 100], [0, 100], [0, 100], ["schooling", "lesson"]),
        ("bn_madison", "See it, wait, leave. That's your job on him.", [0, 100], [0, 100], [0, 55], ["lesson", "schooling"]),
        ("bn_scope", "He has the scope. You don't have to throw him at it.", [55, 100], [40, 100], [40, 100], ["schooling", "show"]),
        ("bn_rain", "If it pops up rain, still walk him first.", [0, 100], [0, 100], [0, 100], ["schooling"]),
        ("bn_evening", "Evening school. Short. Leave with him, then walk out.", [0, 100], [0, 100], [0, 100], ["schooling"]),
    ]
    for ident, text, conf, ride, timing, sess in extras:
        notes.append(
            {
                "id": ident,
                "text": text,
                "session": sess,
                "abbott_confidence": conf,
                "abbott_rideability": ride,
                "madison_timing": timing,
            }
        )
    return notes


def build_lines() -> list[dict]:
    rows: list[dict] = []
    seen: set[str] = set()
    n = 0
    merged: dict[str, list[str]] = {k: list(v) for k, v in LINES.items()}
    for key, texts in MORE.items():
        merged.setdefault(key, []).extend(texts)
    for key, texts in merged.items():
        for i, text in enumerate(texts, 1):
            t = " ".join(text.split())
            if t in seen:
                raise SystemExit(f"duplicate text: {t}")
            seen.add(t)
            wc = word_count(t)
            if wc > MAX_LINE_WORDS:
                raise SystemExit(f"word cap {wc} > {MAX_LINE_WORDS}: {t}")
            session = SESSIONS
            if key == "lesson_start":
                session = ["lesson"]
            elif key == "jump_off":
                session = ["show"]
            elif key in ("ribbon", "off_course", "three", "time"):
                session = ["show"]
            n += 1
            rows.append(
                {
                    "id": f"{key}_{i:02d}",
                    "key": key,
                    "text": t,
                    "session": session,
                    "class_id": CLASSES,
                    "when": "after_leave" if key not in (
                        "lesson_start",
                        "jump_off",
                        "walk_out",
                        "walk_first",
                    ) else "before_round",
                }
            )
    return rows


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    rows = build_lines()
    payload = {
        "voice": "Michelle, Hidden K. Short. True. Never jokes about the horse getting hurt.",
        "lines": rows,
    }
    OUT.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    notes = barn_notes()
    NOTES.write_text(json.dumps({"notes": notes}, indent=2) + "\n", encoding="utf-8")
    print(f"michelle {len(rows)} lines -> {OUT}")
    print(f"barn notes {len(notes)} -> {NOTES}")
    if len(rows) < 400:
        print("UNDER 400 lines")
        return 1
    if len(notes) < 40:
        print("UNDER 40 barn notes")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
